#ifndef CETMODITY_DEFINE_H
#define CETMODITY_DEFINE_H

#define HUMAN_MAX_NAME_LEN 20
#define HUMAN_MAX_PHONE_LEN 10
#define HUMAN_MAX_ADDRESS_LEN 50

#define PRODUCT_MAX_NAME_LEN 40

#endif // !CETMODITY_DEFINE_H
